name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        # TODO:
        # If you require swift 5.10 or later
        # Set this to that version (e.g. swift-version: '5.10')
        # And use swift-actions/setup-swift@v2
        swift-version: '5'
    - name: Build
      run: swift build
    - name: Run Tests
      run: swift test
